package com.student.registration.model;

import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Component("ClassListExample")
public class ClassListExample implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public ClassListExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andClassIdIsNull() {
			addCriterion("CLASS_ID is null");
			return (Criteria) this;
		}

		public Criteria andClassIdIsNotNull() {
			addCriterion("CLASS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andClassIdEqualTo(Integer value) {
			addCriterion("CLASS_ID =", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdNotEqualTo(Integer value) {
			addCriterion("CLASS_ID <>", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdGreaterThan(Integer value) {
			addCriterion("CLASS_ID >", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("CLASS_ID >=", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdLessThan(Integer value) {
			addCriterion("CLASS_ID <", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdLessThanOrEqualTo(Integer value) {
			addCriterion("CLASS_ID <=", value, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdIn(List<Integer> values) {
			addCriterion("CLASS_ID in", values, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdNotIn(List<Integer> values) {
			addCriterion("CLASS_ID not in", values, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdBetween(Integer value1, Integer value2) {
			addCriterion("CLASS_ID between", value1, value2, "classId");
			return (Criteria) this;
		}

		public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
			addCriterion("CLASS_ID not between", value1, value2, "classId");
			return (Criteria) this;
		}

		public Criteria andClassPidIsNull() {
			addCriterion("CLASS_PID is null");
			return (Criteria) this;
		}

		public Criteria andClassPidIsNotNull() {
			addCriterion("CLASS_PID is not null");
			return (Criteria) this;
		}

		public Criteria andClassPidEqualTo(Integer value) {
			addCriterion("CLASS_PID =", value, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidNotEqualTo(Integer value) {
			addCriterion("CLASS_PID <>", value, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidGreaterThan(Integer value) {
			addCriterion("CLASS_PID >", value, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidGreaterThanOrEqualTo(Integer value) {
			addCriterion("CLASS_PID >=", value, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidLessThan(Integer value) {
			addCriterion("CLASS_PID <", value, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidLessThanOrEqualTo(Integer value) {
			addCriterion("CLASS_PID <=", value, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidIn(List<Integer> values) {
			addCriterion("CLASS_PID in", values, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidNotIn(List<Integer> values) {
			addCriterion("CLASS_PID not in", values, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidBetween(Integer value1, Integer value2) {
			addCriterion("CLASS_PID between", value1, value2, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassPidNotBetween(Integer value1, Integer value2) {
			addCriterion("CLASS_PID not between", value1, value2, "classPid");
			return (Criteria) this;
		}

		public Criteria andClassCodeIsNull() {
			addCriterion("CLASS_CODE is null");
			return (Criteria) this;
		}

		public Criteria andClassCodeIsNotNull() {
			addCriterion("CLASS_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andClassCodeEqualTo(String value) {
			addCriterion("CLASS_CODE =", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeNotEqualTo(String value) {
			addCriterion("CLASS_CODE <>", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeGreaterThan(String value) {
			addCriterion("CLASS_CODE >", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CLASS_CODE >=", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeLessThan(String value) {
			addCriterion("CLASS_CODE <", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeLessThanOrEqualTo(String value) {
			addCriterion("CLASS_CODE <=", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeLike(String value) {
			addCriterion("CLASS_CODE like", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeNotLike(String value) {
			addCriterion("CLASS_CODE not like", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeIn(List<String> values) {
			addCriterion("CLASS_CODE in", values, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeNotIn(List<String> values) {
			addCriterion("CLASS_CODE not in", values, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeBetween(String value1, String value2) {
			addCriterion("CLASS_CODE between", value1, value2, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeNotBetween(String value1, String value2) {
			addCriterion("CLASS_CODE not between", value1, value2, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassNoIsNull() {
			addCriterion("CLASS_NO is null");
			return (Criteria) this;
		}

		public Criteria andClassNoIsNotNull() {
			addCriterion("CLASS_NO is not null");
			return (Criteria) this;
		}

		public Criteria andClassNoEqualTo(String value) {
			addCriterion("CLASS_NO =", value, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoNotEqualTo(String value) {
			addCriterion("CLASS_NO <>", value, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoGreaterThan(String value) {
			addCriterion("CLASS_NO >", value, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoGreaterThanOrEqualTo(String value) {
			addCriterion("CLASS_NO >=", value, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoLessThan(String value) {
			addCriterion("CLASS_NO <", value, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoLessThanOrEqualTo(String value) {
			addCriterion("CLASS_NO <=", value, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoLike(String value) {
			addCriterion("CLASS_NO like", value, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoNotLike(String value) {
			addCriterion("CLASS_NO not like", value, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoIn(List<String> values) {
			addCriterion("CLASS_NO in", values, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoNotIn(List<String> values) {
			addCriterion("CLASS_NO not in", values, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoBetween(String value1, String value2) {
			addCriterion("CLASS_NO between", value1, value2, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNoNotBetween(String value1, String value2) {
			addCriterion("CLASS_NO not between", value1, value2, "classNo");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNull() {
			addCriterion("CLASS_NAME is null");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNotNull() {
			addCriterion("CLASS_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andClassNameEqualTo(String value) {
			addCriterion("CLASS_NAME =", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotEqualTo(String value) {
			addCriterion("CLASS_NAME <>", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThan(String value) {
			addCriterion("CLASS_NAME >", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThanOrEqualTo(String value) {
			addCriterion("CLASS_NAME >=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThan(String value) {
			addCriterion("CLASS_NAME <", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThanOrEqualTo(String value) {
			addCriterion("CLASS_NAME <=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLike(String value) {
			addCriterion("CLASS_NAME like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotLike(String value) {
			addCriterion("CLASS_NAME not like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameIn(List<String> values) {
			addCriterion("CLASS_NAME in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotIn(List<String> values) {
			addCriterion("CLASS_NAME not in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameBetween(String value1, String value2) {
			addCriterion("CLASS_NAME between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotBetween(String value1, String value2) {
			addCriterion("CLASS_NAME not between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andAssistantSignIsNull() {
			addCriterion("ASSISTANT_SIGN is null");
			return (Criteria) this;
		}

		public Criteria andAssistantSignIsNotNull() {
			addCriterion("ASSISTANT_SIGN is not null");
			return (Criteria) this;
		}

		public Criteria andAssistantSignEqualTo(String value) {
			addCriterion("ASSISTANT_SIGN =", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignNotEqualTo(String value) {
			addCriterion("ASSISTANT_SIGN <>", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignGreaterThan(String value) {
			addCriterion("ASSISTANT_SIGN >", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignGreaterThanOrEqualTo(String value) {
			addCriterion("ASSISTANT_SIGN >=", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignLessThan(String value) {
			addCriterion("ASSISTANT_SIGN <", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignLessThanOrEqualTo(String value) {
			addCriterion("ASSISTANT_SIGN <=", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignLike(String value) {
			addCriterion("ASSISTANT_SIGN like", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignNotLike(String value) {
			addCriterion("ASSISTANT_SIGN not like", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignIn(List<String> values) {
			addCriterion("ASSISTANT_SIGN in", values, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignNotIn(List<String> values) {
			addCriterion("ASSISTANT_SIGN not in", values, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignBetween(String value1, String value2) {
			addCriterion("ASSISTANT_SIGN between", value1, value2,
					"assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignNotBetween(String value1, String value2) {
			addCriterion("ASSISTANT_SIGN not between", value1, value2,
					"assistantSign");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameIsNull() {
			addCriterion("DEFAULT_STAT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameIsNotNull() {
			addCriterion("DEFAULT_STAT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameEqualTo(String value) {
			addCriterion("DEFAULT_STAT_NAME =", value, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameNotEqualTo(String value) {
			addCriterion("DEFAULT_STAT_NAME <>", value, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameGreaterThan(String value) {
			addCriterion("DEFAULT_STAT_NAME >", value, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameGreaterThanOrEqualTo(String value) {
			addCriterion("DEFAULT_STAT_NAME >=", value, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameLessThan(String value) {
			addCriterion("DEFAULT_STAT_NAME <", value, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameLessThanOrEqualTo(String value) {
			addCriterion("DEFAULT_STAT_NAME <=", value, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameLike(String value) {
			addCriterion("DEFAULT_STAT_NAME like", value, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameNotLike(String value) {
			addCriterion("DEFAULT_STAT_NAME not like", value, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameIn(List<String> values) {
			addCriterion("DEFAULT_STAT_NAME in", values, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameNotIn(List<String> values) {
			addCriterion("DEFAULT_STAT_NAME not in", values, "defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameBetween(String value1, String value2) {
			addCriterion("DEFAULT_STAT_NAME between", value1, value2,
					"defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultStatNameNotBetween(String value1,
				String value2) {
			addCriterion("DEFAULT_STAT_NAME not between", value1, value2,
					"defaultStatName");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckIsNull() {
			addCriterion("DEFAULT_IS_CHECK is null");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckIsNotNull() {
			addCriterion("DEFAULT_IS_CHECK is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckEqualTo(String value) {
			addCriterion("DEFAULT_IS_CHECK =", value, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckNotEqualTo(String value) {
			addCriterion("DEFAULT_IS_CHECK <>", value, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckGreaterThan(String value) {
			addCriterion("DEFAULT_IS_CHECK >", value, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckGreaterThanOrEqualTo(String value) {
			addCriterion("DEFAULT_IS_CHECK >=", value, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckLessThan(String value) {
			addCriterion("DEFAULT_IS_CHECK <", value, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckLessThanOrEqualTo(String value) {
			addCriterion("DEFAULT_IS_CHECK <=", value, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckLike(String value) {
			addCriterion("DEFAULT_IS_CHECK like", value, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckNotLike(String value) {
			addCriterion("DEFAULT_IS_CHECK not like", value, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckIn(List<String> values) {
			addCriterion("DEFAULT_IS_CHECK in", values, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckNotIn(List<String> values) {
			addCriterion("DEFAULT_IS_CHECK not in", values, "defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckBetween(String value1, String value2) {
			addCriterion("DEFAULT_IS_CHECK between", value1, value2,
					"defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultIsCheckNotBetween(String value1, String value2) {
			addCriterion("DEFAULT_IS_CHECK not between", value1, value2,
					"defaultIsCheck");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearIsNull() {
			addCriterion("DEFAULT_USER_YEAR is null");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearIsNotNull() {
			addCriterion("DEFAULT_USER_YEAR is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearEqualTo(Integer value) {
			addCriterion("DEFAULT_USER_YEAR =", value, "defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearNotEqualTo(Integer value) {
			addCriterion("DEFAULT_USER_YEAR <>", value, "defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearGreaterThan(Integer value) {
			addCriterion("DEFAULT_USER_YEAR >", value, "defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearGreaterThanOrEqualTo(Integer value) {
			addCriterion("DEFAULT_USER_YEAR >=", value, "defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearLessThan(Integer value) {
			addCriterion("DEFAULT_USER_YEAR <", value, "defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearLessThanOrEqualTo(Integer value) {
			addCriterion("DEFAULT_USER_YEAR <=", value, "defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearIn(List<Integer> values) {
			addCriterion("DEFAULT_USER_YEAR in", values, "defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearNotIn(List<Integer> values) {
			addCriterion("DEFAULT_USER_YEAR not in", values, "defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearBetween(Integer value1, Integer value2) {
			addCriterion("DEFAULT_USER_YEAR between", value1, value2,
					"defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultUserYearNotBetween(Integer value1,
				Integer value2) {
			addCriterion("DEFAULT_USER_YEAR not between", value1, value2,
					"defaultUserYear");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepIsNull() {
			addCriterion("DEFAULT_IS_DEP is null");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepIsNotNull() {
			addCriterion("DEFAULT_IS_DEP is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepEqualTo(String value) {
			addCriterion("DEFAULT_IS_DEP =", value, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepNotEqualTo(String value) {
			addCriterion("DEFAULT_IS_DEP <>", value, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepGreaterThan(String value) {
			addCriterion("DEFAULT_IS_DEP >", value, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepGreaterThanOrEqualTo(String value) {
			addCriterion("DEFAULT_IS_DEP >=", value, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepLessThan(String value) {
			addCriterion("DEFAULT_IS_DEP <", value, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepLessThanOrEqualTo(String value) {
			addCriterion("DEFAULT_IS_DEP <=", value, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepLike(String value) {
			addCriterion("DEFAULT_IS_DEP like", value, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepNotLike(String value) {
			addCriterion("DEFAULT_IS_DEP not like", value, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepIn(List<String> values) {
			addCriterion("DEFAULT_IS_DEP in", values, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepNotIn(List<String> values) {
			addCriterion("DEFAULT_IS_DEP not in", values, "defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepBetween(String value1, String value2) {
			addCriterion("DEFAULT_IS_DEP between", value1, value2,
					"defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultIsDepNotBetween(String value1, String value2) {
			addCriterion("DEFAULT_IS_DEP not between", value1, value2,
					"defaultIsDep");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueIsNull() {
			addCriterion("DEFAULT_REMAIN_VALUE is null");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueIsNotNull() {
			addCriterion("DEFAULT_REMAIN_VALUE is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueEqualTo(Integer value) {
			addCriterion("DEFAULT_REMAIN_VALUE =", value, "defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueNotEqualTo(Integer value) {
			addCriterion("DEFAULT_REMAIN_VALUE <>", value, "defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueGreaterThan(Integer value) {
			addCriterion("DEFAULT_REMAIN_VALUE >", value, "defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueGreaterThanOrEqualTo(Integer value) {
			addCriterion("DEFAULT_REMAIN_VALUE >=", value, "defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueLessThan(Integer value) {
			addCriterion("DEFAULT_REMAIN_VALUE <", value, "defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueLessThanOrEqualTo(Integer value) {
			addCriterion("DEFAULT_REMAIN_VALUE <=", value, "defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueIn(List<Integer> values) {
			addCriterion("DEFAULT_REMAIN_VALUE in", values,
					"defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueNotIn(List<Integer> values) {
			addCriterion("DEFAULT_REMAIN_VALUE not in", values,
					"defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueBetween(Integer value1,
				Integer value2) {
			addCriterion("DEFAULT_REMAIN_VALUE between", value1, value2,
					"defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultRemainValueNotBetween(Integer value1,
				Integer value2) {
			addCriterion("DEFAULT_REMAIN_VALUE not between", value1, value2,
					"defaultRemainValue");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdIsNull() {
			addCriterion("DEFAULT_ASSET_KIND_ID is null");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdIsNotNull() {
			addCriterion("DEFAULT_ASSET_KIND_ID is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdEqualTo(Integer value) {
			addCriterion("DEFAULT_ASSET_KIND_ID =", value, "defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdNotEqualTo(Integer value) {
			addCriterion("DEFAULT_ASSET_KIND_ID <>", value,
					"defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdGreaterThan(Integer value) {
			addCriterion("DEFAULT_ASSET_KIND_ID >", value, "defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("DEFAULT_ASSET_KIND_ID >=", value,
					"defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdLessThan(Integer value) {
			addCriterion("DEFAULT_ASSET_KIND_ID <", value, "defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdLessThanOrEqualTo(Integer value) {
			addCriterion("DEFAULT_ASSET_KIND_ID <=", value,
					"defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdIn(List<Integer> values) {
			addCriterion("DEFAULT_ASSET_KIND_ID in", values,
					"defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdNotIn(List<Integer> values) {
			addCriterion("DEFAULT_ASSET_KIND_ID not in", values,
					"defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdBetween(Integer value1,
				Integer value2) {
			addCriterion("DEFAULT_ASSET_KIND_ID between", value1, value2,
					"defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDefaultAssetKindIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("DEFAULT_ASSET_KIND_ID not between", value1, value2,
					"defaultAssetKindId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdIsNull() {
			addCriterion("DEPR_TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdIsNotNull() {
			addCriterion("DEPR_TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdEqualTo(Integer value) {
			addCriterion("DEPR_TYPE_ID =", value, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdNotEqualTo(Integer value) {
			addCriterion("DEPR_TYPE_ID <>", value, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdGreaterThan(Integer value) {
			addCriterion("DEPR_TYPE_ID >", value, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("DEPR_TYPE_ID >=", value, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdLessThan(Integer value) {
			addCriterion("DEPR_TYPE_ID <", value, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("DEPR_TYPE_ID <=", value, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdIn(List<Integer> values) {
			addCriterion("DEPR_TYPE_ID in", values, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdNotIn(List<Integer> values) {
			addCriterion("DEPR_TYPE_ID not in", values, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("DEPR_TYPE_ID between", value1, value2, "deprTypeId");
			return (Criteria) this;
		}

		public Criteria andDeprTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("DEPR_TYPE_ID not between", value1, value2,
					"deprTypeId");
			return (Criteria) this;
		}

		public Criteria andIsEnabledIsNull() {
			addCriterion("IS_ENABLED is null");
			return (Criteria) this;
		}

		public Criteria andIsEnabledIsNotNull() {
			addCriterion("IS_ENABLED is not null");
			return (Criteria) this;
		}

		public Criteria andIsEnabledEqualTo(String value) {
			addCriterion("IS_ENABLED =", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledNotEqualTo(String value) {
			addCriterion("IS_ENABLED <>", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledGreaterThan(String value) {
			addCriterion("IS_ENABLED >", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledGreaterThanOrEqualTo(String value) {
			addCriterion("IS_ENABLED >=", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledLessThan(String value) {
			addCriterion("IS_ENABLED <", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledLessThanOrEqualTo(String value) {
			addCriterion("IS_ENABLED <=", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledLike(String value) {
			addCriterion("IS_ENABLED like", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledNotLike(String value) {
			addCriterion("IS_ENABLED not like", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledIn(List<String> values) {
			addCriterion("IS_ENABLED in", values, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledNotIn(List<String> values) {
			addCriterion("IS_ENABLED not in", values, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledBetween(String value1, String value2) {
			addCriterion("IS_ENABLED between", value1, value2, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledNotBetween(String value1, String value2) {
			addCriterion("IS_ENABLED not between", value1, value2, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE not between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateManIsNull() {
			addCriterion("CREATE_MAN is null");
			return (Criteria) this;
		}

		public Criteria andCreateManIsNotNull() {
			addCriterion("CREATE_MAN is not null");
			return (Criteria) this;
		}

		public Criteria andCreateManEqualTo(String value) {
			addCriterion("CREATE_MAN =", value, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManNotEqualTo(String value) {
			addCriterion("CREATE_MAN <>", value, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManGreaterThan(String value) {
			addCriterion("CREATE_MAN >", value, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_MAN >=", value, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManLessThan(String value) {
			addCriterion("CREATE_MAN <", value, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManLessThanOrEqualTo(String value) {
			addCriterion("CREATE_MAN <=", value, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManLike(String value) {
			addCriterion("CREATE_MAN like", value, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManNotLike(String value) {
			addCriterion("CREATE_MAN not like", value, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManIn(List<String> values) {
			addCriterion("CREATE_MAN in", values, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManNotIn(List<String> values) {
			addCriterion("CREATE_MAN not in", values, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManBetween(String value1, String value2) {
			addCriterion("CREATE_MAN between", value1, value2, "createMan");
			return (Criteria) this;
		}

		public Criteria andCreateManNotBetween(String value1, String value2) {
			addCriterion("CREATE_MAN not between", value1, value2, "createMan");
			return (Criteria) this;
		}

		public Criteria andModifyDateIsNull() {
			addCriterion("MODIFY_DATE is null");
			return (Criteria) this;
		}

		public Criteria andModifyDateIsNotNull() {
			addCriterion("MODIFY_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andModifyDateEqualTo(Date value) {
			addCriterion("MODIFY_DATE =", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateNotEqualTo(Date value) {
			addCriterion("MODIFY_DATE <>", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateGreaterThan(Date value) {
			addCriterion("MODIFY_DATE >", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_DATE >=", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateLessThan(Date value) {
			addCriterion("MODIFY_DATE <", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_DATE <=", value, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateIn(List<Date> values) {
			addCriterion("MODIFY_DATE in", values, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateNotIn(List<Date> values) {
			addCriterion("MODIFY_DATE not in", values, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateBetween(Date value1, Date value2) {
			addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyDateNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_DATE not between", value1, value2,
					"modifyDate");
			return (Criteria) this;
		}

		public Criteria andModifyManIsNull() {
			addCriterion("MODIFY_MAN is null");
			return (Criteria) this;
		}

		public Criteria andModifyManIsNotNull() {
			addCriterion("MODIFY_MAN is not null");
			return (Criteria) this;
		}

		public Criteria andModifyManEqualTo(String value) {
			addCriterion("MODIFY_MAN =", value, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManNotEqualTo(String value) {
			addCriterion("MODIFY_MAN <>", value, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManGreaterThan(String value) {
			addCriterion("MODIFY_MAN >", value, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_MAN >=", value, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManLessThan(String value) {
			addCriterion("MODIFY_MAN <", value, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_MAN <=", value, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManLike(String value) {
			addCriterion("MODIFY_MAN like", value, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManNotLike(String value) {
			addCriterion("MODIFY_MAN not like", value, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManIn(List<String> values) {
			addCriterion("MODIFY_MAN in", values, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManNotIn(List<String> values) {
			addCriterion("MODIFY_MAN not in", values, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManBetween(String value1, String value2) {
			addCriterion("MODIFY_MAN between", value1, value2, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andModifyManNotBetween(String value1, String value2) {
			addCriterion("MODIFY_MAN not between", value1, value2, "modifyMan");
			return (Criteria) this;
		}

		public Criteria andExplainationIsNull() {
			addCriterion("EXPLAINATION is null");
			return (Criteria) this;
		}

		public Criteria andExplainationIsNotNull() {
			addCriterion("EXPLAINATION is not null");
			return (Criteria) this;
		}

		public Criteria andExplainationEqualTo(String value) {
			addCriterion("EXPLAINATION =", value, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationNotEqualTo(String value) {
			addCriterion("EXPLAINATION <>", value, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationGreaterThan(String value) {
			addCriterion("EXPLAINATION >", value, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationGreaterThanOrEqualTo(String value) {
			addCriterion("EXPLAINATION >=", value, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationLessThan(String value) {
			addCriterion("EXPLAINATION <", value, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationLessThanOrEqualTo(String value) {
			addCriterion("EXPLAINATION <=", value, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationLike(String value) {
			addCriterion("EXPLAINATION like", value, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationNotLike(String value) {
			addCriterion("EXPLAINATION not like", value, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationIn(List<String> values) {
			addCriterion("EXPLAINATION in", values, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationNotIn(List<String> values) {
			addCriterion("EXPLAINATION not in", values, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationBetween(String value1, String value2) {
			addCriterion("EXPLAINATION between", value1, value2, "explaination");
			return (Criteria) this;
		}

		public Criteria andExplainationNotBetween(String value1, String value2) {
			addCriterion("EXPLAINATION not between", value1, value2,
					"explaination");
			return (Criteria) this;
		}

		public Criteria andSortIsNull() {
			addCriterion("SORT is null");
			return (Criteria) this;
		}

		public Criteria andSortIsNotNull() {
			addCriterion("SORT is not null");
			return (Criteria) this;
		}

		public Criteria andSortEqualTo(Integer value) {
			addCriterion("SORT =", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotEqualTo(Integer value) {
			addCriterion("SORT <>", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThan(Integer value) {
			addCriterion("SORT >", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("SORT >=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThan(Integer value) {
			addCriterion("SORT <", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThanOrEqualTo(Integer value) {
			addCriterion("SORT <=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortIn(List<Integer> values) {
			addCriterion("SORT in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotIn(List<Integer> values) {
			addCriterion("SORT not in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortBetween(Integer value1, Integer value2) {
			addCriterion("SORT between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotBetween(Integer value1, Integer value2) {
			addCriterion("SORT not between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andIsMeasureIsNull() {
			addCriterion("IS_MEASURE is null");
			return (Criteria) this;
		}

		public Criteria andIsMeasureIsNotNull() {
			addCriterion("IS_MEASURE is not null");
			return (Criteria) this;
		}

		public Criteria andIsMeasureEqualTo(String value) {
			addCriterion("IS_MEASURE =", value, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureNotEqualTo(String value) {
			addCriterion("IS_MEASURE <>", value, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureGreaterThan(String value) {
			addCriterion("IS_MEASURE >", value, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureGreaterThanOrEqualTo(String value) {
			addCriterion("IS_MEASURE >=", value, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureLessThan(String value) {
			addCriterion("IS_MEASURE <", value, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureLessThanOrEqualTo(String value) {
			addCriterion("IS_MEASURE <=", value, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureLike(String value) {
			addCriterion("IS_MEASURE like", value, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureNotLike(String value) {
			addCriterion("IS_MEASURE not like", value, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureIn(List<String> values) {
			addCriterion("IS_MEASURE in", values, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureNotIn(List<String> values) {
			addCriterion("IS_MEASURE not in", values, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureBetween(String value1, String value2) {
			addCriterion("IS_MEASURE between", value1, value2, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMeasureNotBetween(String value1, String value2) {
			addCriterion("IS_MEASURE not between", value1, value2, "isMeasure");
			return (Criteria) this;
		}

		public Criteria andIsMaintainIsNull() {
			addCriterion("IS_MAINTAIN is null");
			return (Criteria) this;
		}

		public Criteria andIsMaintainIsNotNull() {
			addCriterion("IS_MAINTAIN is not null");
			return (Criteria) this;
		}

		public Criteria andIsMaintainEqualTo(String value) {
			addCriterion("IS_MAINTAIN =", value, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainNotEqualTo(String value) {
			addCriterion("IS_MAINTAIN <>", value, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainGreaterThan(String value) {
			addCriterion("IS_MAINTAIN >", value, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainGreaterThanOrEqualTo(String value) {
			addCriterion("IS_MAINTAIN >=", value, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainLessThan(String value) {
			addCriterion("IS_MAINTAIN <", value, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainLessThanOrEqualTo(String value) {
			addCriterion("IS_MAINTAIN <=", value, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainLike(String value) {
			addCriterion("IS_MAINTAIN like", value, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainNotLike(String value) {
			addCriterion("IS_MAINTAIN not like", value, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainIn(List<String> values) {
			addCriterion("IS_MAINTAIN in", values, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainNotIn(List<String> values) {
			addCriterion("IS_MAINTAIN not in", values, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainBetween(String value1, String value2) {
			addCriterion("IS_MAINTAIN between", value1, value2, "isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsMaintainNotBetween(String value1, String value2) {
			addCriterion("IS_MAINTAIN not between", value1, value2,
					"isMaintain");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulIsNull() {
			addCriterion("IS_OVERHAUL is null");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulIsNotNull() {
			addCriterion("IS_OVERHAUL is not null");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulEqualTo(String value) {
			addCriterion("IS_OVERHAUL =", value, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulNotEqualTo(String value) {
			addCriterion("IS_OVERHAUL <>", value, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulGreaterThan(String value) {
			addCriterion("IS_OVERHAUL >", value, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulGreaterThanOrEqualTo(String value) {
			addCriterion("IS_OVERHAUL >=", value, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulLessThan(String value) {
			addCriterion("IS_OVERHAUL <", value, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulLessThanOrEqualTo(String value) {
			addCriterion("IS_OVERHAUL <=", value, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulLike(String value) {
			addCriterion("IS_OVERHAUL like", value, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulNotLike(String value) {
			addCriterion("IS_OVERHAUL not like", value, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulIn(List<String> values) {
			addCriterion("IS_OVERHAUL in", values, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulNotIn(List<String> values) {
			addCriterion("IS_OVERHAUL not in", values, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulBetween(String value1, String value2) {
			addCriterion("IS_OVERHAUL between", value1, value2, "isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsOverhaulNotBetween(String value1, String value2) {
			addCriterion("IS_OVERHAUL not between", value1, value2,
					"isOverhaul");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckIsNull() {
			addCriterion("IS_YEAR_CHECK is null");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckIsNotNull() {
			addCriterion("IS_YEAR_CHECK is not null");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckEqualTo(String value) {
			addCriterion("IS_YEAR_CHECK =", value, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckNotEqualTo(String value) {
			addCriterion("IS_YEAR_CHECK <>", value, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckGreaterThan(String value) {
			addCriterion("IS_YEAR_CHECK >", value, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckGreaterThanOrEqualTo(String value) {
			addCriterion("IS_YEAR_CHECK >=", value, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckLessThan(String value) {
			addCriterion("IS_YEAR_CHECK <", value, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckLessThanOrEqualTo(String value) {
			addCriterion("IS_YEAR_CHECK <=", value, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckLike(String value) {
			addCriterion("IS_YEAR_CHECK like", value, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckNotLike(String value) {
			addCriterion("IS_YEAR_CHECK not like", value, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckIn(List<String> values) {
			addCriterion("IS_YEAR_CHECK in", values, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckNotIn(List<String> values) {
			addCriterion("IS_YEAR_CHECK not in", values, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckBetween(String value1, String value2) {
			addCriterion("IS_YEAR_CHECK between", value1, value2, "isYearCheck");
			return (Criteria) this;
		}

		public Criteria andIsYearCheckNotBetween(String value1, String value2) {
			addCriterion("IS_YEAR_CHECK not between", value1, value2,
					"isYearCheck");
			return (Criteria) this;
		}

		public Criteria andClassTypeIsNull() {
			addCriterion("CLASS_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andClassTypeIsNotNull() {
			addCriterion("CLASS_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andClassTypeEqualTo(String value) {
			addCriterion("CLASS_TYPE =", value, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeNotEqualTo(String value) {
			addCriterion("CLASS_TYPE <>", value, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeGreaterThan(String value) {
			addCriterion("CLASS_TYPE >", value, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeGreaterThanOrEqualTo(String value) {
			addCriterion("CLASS_TYPE >=", value, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeLessThan(String value) {
			addCriterion("CLASS_TYPE <", value, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeLessThanOrEqualTo(String value) {
			addCriterion("CLASS_TYPE <=", value, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeLike(String value) {
			addCriterion("CLASS_TYPE like", value, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeNotLike(String value) {
			addCriterion("CLASS_TYPE not like", value, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeIn(List<String> values) {
			addCriterion("CLASS_TYPE in", values, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeNotIn(List<String> values) {
			addCriterion("CLASS_TYPE not in", values, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeBetween(String value1, String value2) {
			addCriterion("CLASS_TYPE between", value1, value2, "classType");
			return (Criteria) this;
		}

		public Criteria andClassTypeNotBetween(String value1, String value2) {
			addCriterion("CLASS_TYPE not between", value1, value2, "classType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table class_list
	 * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class_list
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 30 20:04:42 CST 2014
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

	//@CodeGen 手动添加或生成 begin
	protected int start;
	protected int offset;

	public int getOffset() {
		return offset;
	}

	public void setOffset(int offset) {
		this.offset = offset;
	}

	public int getStart() {
		return start;
	}

	public void setStart(int start) {
		this.start = start;
	}
    //@CodeGen 手动添加或生成 end
}