package com.canco.assetstockin.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AssetListExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public AssetListExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andAssetIdIsNull() {
			addCriterion("asset_id is null");
			return (Criteria) this;
		}

		public Criteria andAssetIdIsNotNull() {
			addCriterion("asset_id is not null");
			return (Criteria) this;
		}

		public Criteria andAssetIdEqualTo(Integer value) {
			addCriterion("asset_id =", value, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdNotEqualTo(Integer value) {
			addCriterion("asset_id <>", value, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdGreaterThan(Integer value) {
			addCriterion("asset_id >", value, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("asset_id >=", value, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdLessThan(Integer value) {
			addCriterion("asset_id <", value, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdLessThanOrEqualTo(Integer value) {
			addCriterion("asset_id <=", value, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdIn(List<Integer> values) {
			addCriterion("asset_id in", values, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdNotIn(List<Integer> values) {
			addCriterion("asset_id not in", values, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdBetween(Integer value1, Integer value2) {
			addCriterion("asset_id between", value1, value2, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetIdNotBetween(Integer value1, Integer value2) {
			addCriterion("asset_id not between", value1, value2, "assetId");
			return (Criteria) this;
		}

		public Criteria andAssetPidIsNull() {
			addCriterion("asset_pid is null");
			return (Criteria) this;
		}

		public Criteria andAssetPidIsNotNull() {
			addCriterion("asset_pid is not null");
			return (Criteria) this;
		}

		public Criteria andAssetPidEqualTo(Integer value) {
			addCriterion("asset_pid =", value, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidNotEqualTo(Integer value) {
			addCriterion("asset_pid <>", value, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidGreaterThan(Integer value) {
			addCriterion("asset_pid >", value, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidGreaterThanOrEqualTo(Integer value) {
			addCriterion("asset_pid >=", value, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidLessThan(Integer value) {
			addCriterion("asset_pid <", value, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidLessThanOrEqualTo(Integer value) {
			addCriterion("asset_pid <=", value, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidIn(List<Integer> values) {
			addCriterion("asset_pid in", values, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidNotIn(List<Integer> values) {
			addCriterion("asset_pid not in", values, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidBetween(Integer value1, Integer value2) {
			addCriterion("asset_pid between", value1, value2, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetPidNotBetween(Integer value1, Integer value2) {
			addCriterion("asset_pid not between", value1, value2, "assetPid");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdIsNull() {
			addCriterion("asset_organ_id is null");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdIsNotNull() {
			addCriterion("asset_organ_id is not null");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdEqualTo(Integer value) {
			addCriterion("asset_organ_id =", value, "assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdNotEqualTo(Integer value) {
			addCriterion("asset_organ_id <>", value, "assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdGreaterThan(Integer value) {
			addCriterion("asset_organ_id >", value, "assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("asset_organ_id >=", value, "assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdLessThan(Integer value) {
			addCriterion("asset_organ_id <", value, "assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdLessThanOrEqualTo(Integer value) {
			addCriterion("asset_organ_id <=", value, "assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdIn(List<Integer> values) {
			addCriterion("asset_organ_id in", values, "assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdNotIn(List<Integer> values) {
			addCriterion("asset_organ_id not in", values, "assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdBetween(Integer value1, Integer value2) {
			addCriterion("asset_organ_id between", value1, value2,
					"assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetOrganIdNotBetween(Integer value1, Integer value2) {
			addCriterion("asset_organ_id not between", value1, value2,
					"assetOrganId");
			return (Criteria) this;
		}

		public Criteria andAssetNoIsNull() {
			addCriterion("asset_no is null");
			return (Criteria) this;
		}

		public Criteria andAssetNoIsNotNull() {
			addCriterion("asset_no is not null");
			return (Criteria) this;
		}

		public Criteria andAssetNoEqualTo(String value) {
			addCriterion("asset_no =", value, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoNotEqualTo(String value) {
			addCriterion("asset_no <>", value, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoGreaterThan(String value) {
			addCriterion("asset_no >", value, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoGreaterThanOrEqualTo(String value) {
			addCriterion("asset_no >=", value, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoLessThan(String value) {
			addCriterion("asset_no <", value, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoLessThanOrEqualTo(String value) {
			addCriterion("asset_no <=", value, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoLike(String value) {
			addCriterion("asset_no like", value, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoNotLike(String value) {
			addCriterion("asset_no not like", value, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoIn(List<String> values) {
			addCriterion("asset_no in", values, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoNotIn(List<String> values) {
			addCriterion("asset_no not in", values, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoBetween(String value1, String value2) {
			addCriterion("asset_no between", value1, value2, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetNoNotBetween(String value1, String value2) {
			addCriterion("asset_no not between", value1, value2, "assetNo");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeIsNull() {
			addCriterion("asset_barcode is null");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeIsNotNull() {
			addCriterion("asset_barcode is not null");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeEqualTo(String value) {
			addCriterion("asset_barcode =", value, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeNotEqualTo(String value) {
			addCriterion("asset_barcode <>", value, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeGreaterThan(String value) {
			addCriterion("asset_barcode >", value, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeGreaterThanOrEqualTo(String value) {
			addCriterion("asset_barcode >=", value, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeLessThan(String value) {
			addCriterion("asset_barcode <", value, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeLessThanOrEqualTo(String value) {
			addCriterion("asset_barcode <=", value, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeLike(String value) {
			addCriterion("asset_barcode like", value, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeNotLike(String value) {
			addCriterion("asset_barcode not like", value, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeIn(List<String> values) {
			addCriterion("asset_barcode in", values, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeNotIn(List<String> values) {
			addCriterion("asset_barcode not in", values, "assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeBetween(String value1, String value2) {
			addCriterion("asset_barcode between", value1, value2,
					"assetBarcode");
			return (Criteria) this;
		}

		public Criteria andAssetBarcodeNotBetween(String value1, String value2) {
			addCriterion("asset_barcode not between", value1, value2,
					"assetBarcode");
			return (Criteria) this;
		}

		public Criteria andMachineNoIsNull() {
			addCriterion("machine_no is null");
			return (Criteria) this;
		}

		public Criteria andMachineNoIsNotNull() {
			addCriterion("machine_no is not null");
			return (Criteria) this;
		}

		public Criteria andMachineNoEqualTo(String value) {
			addCriterion("machine_no =", value, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoNotEqualTo(String value) {
			addCriterion("machine_no <>", value, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoGreaterThan(String value) {
			addCriterion("machine_no >", value, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoGreaterThanOrEqualTo(String value) {
			addCriterion("machine_no >=", value, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoLessThan(String value) {
			addCriterion("machine_no <", value, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoLessThanOrEqualTo(String value) {
			addCriterion("machine_no <=", value, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoLike(String value) {
			addCriterion("machine_no like", value, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoNotLike(String value) {
			addCriterion("machine_no not like", value, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoIn(List<String> values) {
			addCriterion("machine_no in", values, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoNotIn(List<String> values) {
			addCriterion("machine_no not in", values, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoBetween(String value1, String value2) {
			addCriterion("machine_no between", value1, value2, "machineNo");
			return (Criteria) this;
		}

		public Criteria andMachineNoNotBetween(String value1, String value2) {
			addCriterion("machine_no not between", value1, value2, "machineNo");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdIsNull() {
			addCriterion("asset_class_id is null");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdIsNotNull() {
			addCriterion("asset_class_id is not null");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdEqualTo(Integer value) {
			addCriterion("asset_class_id =", value, "assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdNotEqualTo(Integer value) {
			addCriterion("asset_class_id <>", value, "assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdGreaterThan(Integer value) {
			addCriterion("asset_class_id >", value, "assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("asset_class_id >=", value, "assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdLessThan(Integer value) {
			addCriterion("asset_class_id <", value, "assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdLessThanOrEqualTo(Integer value) {
			addCriterion("asset_class_id <=", value, "assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdIn(List<Integer> values) {
			addCriterion("asset_class_id in", values, "assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdNotIn(List<Integer> values) {
			addCriterion("asset_class_id not in", values, "assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdBetween(Integer value1, Integer value2) {
			addCriterion("asset_class_id between", value1, value2,
					"assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetClassIdNotBetween(Integer value1, Integer value2) {
			addCriterion("asset_class_id not between", value1, value2,
					"assetClassId");
			return (Criteria) this;
		}

		public Criteria andAssetNameIsNull() {
			addCriterion("asset_name is null");
			return (Criteria) this;
		}

		public Criteria andAssetNameIsNotNull() {
			addCriterion("asset_name is not null");
			return (Criteria) this;
		}

		public Criteria andAssetNameEqualTo(String value) {
			addCriterion("asset_name =", value, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameNotEqualTo(String value) {
			addCriterion("asset_name <>", value, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameGreaterThan(String value) {
			addCriterion("asset_name >", value, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameGreaterThanOrEqualTo(String value) {
			addCriterion("asset_name >=", value, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameLessThan(String value) {
			addCriterion("asset_name <", value, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameLessThanOrEqualTo(String value) {
			addCriterion("asset_name <=", value, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameLike(String value) {
			addCriterion("asset_name like", value, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameNotLike(String value) {
			addCriterion("asset_name not like", value, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameIn(List<String> values) {
			addCriterion("asset_name in", values, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameNotIn(List<String> values) {
			addCriterion("asset_name not in", values, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameBetween(String value1, String value2) {
			addCriterion("asset_name between", value1, value2, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssetNameNotBetween(String value1, String value2) {
			addCriterion("asset_name not between", value1, value2, "assetName");
			return (Criteria) this;
		}

		public Criteria andAssistantSignIsNull() {
			addCriterion("assistant_sign is null");
			return (Criteria) this;
		}

		public Criteria andAssistantSignIsNotNull() {
			addCriterion("assistant_sign is not null");
			return (Criteria) this;
		}

		public Criteria andAssistantSignEqualTo(String value) {
			addCriterion("assistant_sign =", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignNotEqualTo(String value) {
			addCriterion("assistant_sign <>", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignGreaterThan(String value) {
			addCriterion("assistant_sign >", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignGreaterThanOrEqualTo(String value) {
			addCriterion("assistant_sign >=", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignLessThan(String value) {
			addCriterion("assistant_sign <", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignLessThanOrEqualTo(String value) {
			addCriterion("assistant_sign <=", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignLike(String value) {
			addCriterion("assistant_sign like", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignNotLike(String value) {
			addCriterion("assistant_sign not like", value, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignIn(List<String> values) {
			addCriterion("assistant_sign in", values, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignNotIn(List<String> values) {
			addCriterion("assistant_sign not in", values, "assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignBetween(String value1, String value2) {
			addCriterion("assistant_sign between", value1, value2,
					"assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssistantSignNotBetween(String value1, String value2) {
			addCriterion("assistant_sign not between", value1, value2,
					"assistantSign");
			return (Criteria) this;
		}

		public Criteria andAssetBrandIsNull() {
			addCriterion("asset_brand is null");
			return (Criteria) this;
		}

		public Criteria andAssetBrandIsNotNull() {
			addCriterion("asset_brand is not null");
			return (Criteria) this;
		}

		public Criteria andAssetBrandEqualTo(String value) {
			addCriterion("asset_brand =", value, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandNotEqualTo(String value) {
			addCriterion("asset_brand <>", value, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandGreaterThan(String value) {
			addCriterion("asset_brand >", value, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandGreaterThanOrEqualTo(String value) {
			addCriterion("asset_brand >=", value, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandLessThan(String value) {
			addCriterion("asset_brand <", value, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandLessThanOrEqualTo(String value) {
			addCriterion("asset_brand <=", value, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandLike(String value) {
			addCriterion("asset_brand like", value, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandNotLike(String value) {
			addCriterion("asset_brand not like", value, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandIn(List<String> values) {
			addCriterion("asset_brand in", values, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandNotIn(List<String> values) {
			addCriterion("asset_brand not in", values, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandBetween(String value1, String value2) {
			addCriterion("asset_brand between", value1, value2, "assetBrand");
			return (Criteria) this;
		}

		public Criteria andAssetBrandNotBetween(String value1, String value2) {
			addCriterion("asset_brand not between", value1, value2,
					"assetBrand");
			return (Criteria) this;
		}

		public Criteria andSpecModelIsNull() {
			addCriterion("spec_model is null");
			return (Criteria) this;
		}

		public Criteria andSpecModelIsNotNull() {
			addCriterion("spec_model is not null");
			return (Criteria) this;
		}

		public Criteria andSpecModelEqualTo(String value) {
			addCriterion("spec_model =", value, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelNotEqualTo(String value) {
			addCriterion("spec_model <>", value, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelGreaterThan(String value) {
			addCriterion("spec_model >", value, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelGreaterThanOrEqualTo(String value) {
			addCriterion("spec_model >=", value, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelLessThan(String value) {
			addCriterion("spec_model <", value, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelLessThanOrEqualTo(String value) {
			addCriterion("spec_model <=", value, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelLike(String value) {
			addCriterion("spec_model like", value, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelNotLike(String value) {
			addCriterion("spec_model not like", value, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelIn(List<String> values) {
			addCriterion("spec_model in", values, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelNotIn(List<String> values) {
			addCriterion("spec_model not in", values, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelBetween(String value1, String value2) {
			addCriterion("spec_model between", value1, value2, "specModel");
			return (Criteria) this;
		}

		public Criteria andSpecModelNotBetween(String value1, String value2) {
			addCriterion("spec_model not between", value1, value2, "specModel");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdIsNull() {
			addCriterion("purchase_id is null");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdIsNotNull() {
			addCriterion("purchase_id is not null");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdEqualTo(Integer value) {
			addCriterion("purchase_id =", value, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdNotEqualTo(Integer value) {
			addCriterion("purchase_id <>", value, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdGreaterThan(Integer value) {
			addCriterion("purchase_id >", value, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("purchase_id >=", value, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdLessThan(Integer value) {
			addCriterion("purchase_id <", value, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdLessThanOrEqualTo(Integer value) {
			addCriterion("purchase_id <=", value, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdIn(List<Integer> values) {
			addCriterion("purchase_id in", values, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdNotIn(List<Integer> values) {
			addCriterion("purchase_id not in", values, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdBetween(Integer value1, Integer value2) {
			addCriterion("purchase_id between", value1, value2, "purchaseId");
			return (Criteria) this;
		}

		public Criteria andPurchaseIdNotBetween(Integer value1, Integer value2) {
			addCriterion("purchase_id not between", value1, value2,
					"purchaseId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdIsNull() {
			addCriterion("scrap_type_id is null");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdIsNotNull() {
			addCriterion("scrap_type_id is not null");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdEqualTo(Integer value) {
			addCriterion("scrap_type_id =", value, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdNotEqualTo(Integer value) {
			addCriterion("scrap_type_id <>", value, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdGreaterThan(Integer value) {
			addCriterion("scrap_type_id >", value, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("scrap_type_id >=", value, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdLessThan(Integer value) {
			addCriterion("scrap_type_id <", value, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("scrap_type_id <=", value, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdIn(List<Integer> values) {
			addCriterion("scrap_type_id in", values, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdNotIn(List<Integer> values) {
			addCriterion("scrap_type_id not in", values, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("scrap_type_id between", value1, value2, "scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andScrapTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("scrap_type_id not between", value1, value2,
					"scrapTypeId");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateIsNull() {
			addCriterion("purchase_date is null");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateIsNotNull() {
			addCriterion("purchase_date is not null");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateEqualTo(Date value) {
			addCriterionForJDBCDate("purchase_date =", value, "purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("purchase_date <>", value, "purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateGreaterThan(Date value) {
			addCriterionForJDBCDate("purchase_date >", value, "purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("purchase_date >=", value, "purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateLessThan(Date value) {
			addCriterionForJDBCDate("purchase_date <", value, "purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("purchase_date <=", value, "purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateIn(List<Date> values) {
			addCriterionForJDBCDate("purchase_date in", values, "purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("purchase_date not in", values,
					"purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("purchase_date between", value1, value2,
					"purchaseDate");
			return (Criteria) this;
		}

		public Criteria andPurchaseDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("purchase_date not between", value1,
					value2, "purchaseDate");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodIsNull() {
			addCriterion("warranty_period is null");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodIsNotNull() {
			addCriterion("warranty_period is not null");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodEqualTo(Short value) {
			addCriterion("warranty_period =", value, "warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodNotEqualTo(Short value) {
			addCriterion("warranty_period <>", value, "warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodGreaterThan(Short value) {
			addCriterion("warranty_period >", value, "warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodGreaterThanOrEqualTo(Short value) {
			addCriterion("warranty_period >=", value, "warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodLessThan(Short value) {
			addCriterion("warranty_period <", value, "warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodLessThanOrEqualTo(Short value) {
			addCriterion("warranty_period <=", value, "warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodIn(List<Short> values) {
			addCriterion("warranty_period in", values, "warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodNotIn(List<Short> values) {
			addCriterion("warranty_period not in", values, "warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodBetween(Short value1, Short value2) {
			addCriterion("warranty_period between", value1, value2,
					"warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andWarrantyPeriodNotBetween(Short value1, Short value2) {
			addCriterion("warranty_period not between", value1, value2,
					"warrantyPeriod");
			return (Criteria) this;
		}

		public Criteria andServiceLifeIsNull() {
			addCriterion("service_life is null");
			return (Criteria) this;
		}

		public Criteria andServiceLifeIsNotNull() {
			addCriterion("service_life is not null");
			return (Criteria) this;
		}

		public Criteria andServiceLifeEqualTo(Short value) {
			addCriterion("service_life =", value, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeNotEqualTo(Short value) {
			addCriterion("service_life <>", value, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeGreaterThan(Short value) {
			addCriterion("service_life >", value, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeGreaterThanOrEqualTo(Short value) {
			addCriterion("service_life >=", value, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeLessThan(Short value) {
			addCriterion("service_life <", value, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeLessThanOrEqualTo(Short value) {
			addCriterion("service_life <=", value, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeIn(List<Short> values) {
			addCriterion("service_life in", values, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeNotIn(List<Short> values) {
			addCriterion("service_life not in", values, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeBetween(Short value1, Short value2) {
			addCriterion("service_life between", value1, value2, "serviceLife");
			return (Criteria) this;
		}

		public Criteria andServiceLifeNotBetween(Short value1, Short value2) {
			addCriterion("service_life not between", value1, value2,
					"serviceLife");
			return (Criteria) this;
		}

		public Criteria andQuantityNumIsNull() {
			addCriterion("quantity_num is null");
			return (Criteria) this;
		}

		public Criteria andQuantityNumIsNotNull() {
			addCriterion("quantity_num is not null");
			return (Criteria) this;
		}

		public Criteria andQuantityNumEqualTo(BigDecimal value) {
			addCriterion("quantity_num =", value, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumNotEqualTo(BigDecimal value) {
			addCriterion("quantity_num <>", value, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumGreaterThan(BigDecimal value) {
			addCriterion("quantity_num >", value, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("quantity_num >=", value, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumLessThan(BigDecimal value) {
			addCriterion("quantity_num <", value, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumLessThanOrEqualTo(BigDecimal value) {
			addCriterion("quantity_num <=", value, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumIn(List<BigDecimal> values) {
			addCriterion("quantity_num in", values, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumNotIn(List<BigDecimal> values) {
			addCriterion("quantity_num not in", values, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("quantity_num between", value1, value2, "quantityNum");
			return (Criteria) this;
		}

		public Criteria andQuantityNumNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("quantity_num not between", value1, value2,
					"quantityNum");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitIsNull() {
			addCriterion("measurement_unit is null");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitIsNotNull() {
			addCriterion("measurement_unit is not null");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitEqualTo(String value) {
			addCriterion("measurement_unit =", value, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitNotEqualTo(String value) {
			addCriterion("measurement_unit <>", value, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitGreaterThan(String value) {
			addCriterion("measurement_unit >", value, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitGreaterThanOrEqualTo(String value) {
			addCriterion("measurement_unit >=", value, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitLessThan(String value) {
			addCriterion("measurement_unit <", value, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitLessThanOrEqualTo(String value) {
			addCriterion("measurement_unit <=", value, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitLike(String value) {
			addCriterion("measurement_unit like", value, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitNotLike(String value) {
			addCriterion("measurement_unit not like", value, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitIn(List<String> values) {
			addCriterion("measurement_unit in", values, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitNotIn(List<String> values) {
			addCriterion("measurement_unit not in", values, "measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitBetween(String value1, String value2) {
			addCriterion("measurement_unit between", value1, value2,
					"measurementUnit");
			return (Criteria) this;
		}

		public Criteria andMeasurementUnitNotBetween(String value1,
				String value2) {
			addCriterion("measurement_unit not between", value1, value2,
					"measurementUnit");
			return (Criteria) this;
		}

		public Criteria andOriginalValueIsNull() {
			addCriterion("original_value is null");
			return (Criteria) this;
		}

		public Criteria andOriginalValueIsNotNull() {
			addCriterion("original_value is not null");
			return (Criteria) this;
		}

		public Criteria andOriginalValueEqualTo(BigDecimal value) {
			addCriterion("original_value =", value, "originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueNotEqualTo(BigDecimal value) {
			addCriterion("original_value <>", value, "originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueGreaterThan(BigDecimal value) {
			addCriterion("original_value >", value, "originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("original_value >=", value, "originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueLessThan(BigDecimal value) {
			addCriterion("original_value <", value, "originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueLessThanOrEqualTo(BigDecimal value) {
			addCriterion("original_value <=", value, "originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueIn(List<BigDecimal> values) {
			addCriterion("original_value in", values, "originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueNotIn(List<BigDecimal> values) {
			addCriterion("original_value not in", values, "originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("original_value between", value1, value2,
					"originalValue");
			return (Criteria) this;
		}

		public Criteria andOriginalValueNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("original_value not between", value1, value2,
					"originalValue");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdIsNull() {
			addCriterion("depositary_id is null");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdIsNotNull() {
			addCriterion("depositary_id is not null");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdEqualTo(Integer value) {
			addCriterion("depositary_id =", value, "depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdNotEqualTo(Integer value) {
			addCriterion("depositary_id <>", value, "depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdGreaterThan(Integer value) {
			addCriterion("depositary_id >", value, "depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("depositary_id >=", value, "depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdLessThan(Integer value) {
			addCriterion("depositary_id <", value, "depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdLessThanOrEqualTo(Integer value) {
			addCriterion("depositary_id <=", value, "depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdIn(List<Integer> values) {
			addCriterion("depositary_id in", values, "depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdNotIn(List<Integer> values) {
			addCriterion("depositary_id not in", values, "depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdBetween(Integer value1, Integer value2) {
			addCriterion("depositary_id between", value1, value2,
					"depositaryId");
			return (Criteria) this;
		}

		public Criteria andDepositaryIdNotBetween(Integer value1, Integer value2) {
			addCriterion("depositary_id not between", value1, value2,
					"depositaryId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdIsNull() {
			addCriterion("keep_unit_id is null");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdIsNotNull() {
			addCriterion("keep_unit_id is not null");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdEqualTo(Integer value) {
			addCriterion("keep_unit_id =", value, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdNotEqualTo(Integer value) {
			addCriterion("keep_unit_id <>", value, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdGreaterThan(Integer value) {
			addCriterion("keep_unit_id >", value, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("keep_unit_id >=", value, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdLessThan(Integer value) {
			addCriterion("keep_unit_id <", value, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdLessThanOrEqualTo(Integer value) {
			addCriterion("keep_unit_id <=", value, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdIn(List<Integer> values) {
			addCriterion("keep_unit_id in", values, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdNotIn(List<Integer> values) {
			addCriterion("keep_unit_id not in", values, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdBetween(Integer value1, Integer value2) {
			addCriterion("keep_unit_id between", value1, value2, "keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepUnitIdNotBetween(Integer value1, Integer value2) {
			addCriterion("keep_unit_id not between", value1, value2,
					"keepUnitId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdIsNull() {
			addCriterion("keep_employee_id is null");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdIsNotNull() {
			addCriterion("keep_employee_id is not null");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdEqualTo(Integer value) {
			addCriterion("keep_employee_id =", value, "keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdNotEqualTo(Integer value) {
			addCriterion("keep_employee_id <>", value, "keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdGreaterThan(Integer value) {
			addCriterion("keep_employee_id >", value, "keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("keep_employee_id >=", value, "keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdLessThan(Integer value) {
			addCriterion("keep_employee_id <", value, "keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdLessThanOrEqualTo(Integer value) {
			addCriterion("keep_employee_id <=", value, "keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdIn(List<Integer> values) {
			addCriterion("keep_employee_id in", values, "keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdNotIn(List<Integer> values) {
			addCriterion("keep_employee_id not in", values, "keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdBetween(Integer value1, Integer value2) {
			addCriterion("keep_employee_id between", value1, value2,
					"keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andKeepEmployeeIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("keep_employee_id not between", value1, value2,
					"keepEmployeeId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdIsNull() {
			addCriterion("asset_state_id is null");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdIsNotNull() {
			addCriterion("asset_state_id is not null");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdEqualTo(Integer value) {
			addCriterion("asset_state_id =", value, "assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdNotEqualTo(Integer value) {
			addCriterion("asset_state_id <>", value, "assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdGreaterThan(Integer value) {
			addCriterion("asset_state_id >", value, "assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("asset_state_id >=", value, "assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdLessThan(Integer value) {
			addCriterion("asset_state_id <", value, "assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdLessThanOrEqualTo(Integer value) {
			addCriterion("asset_state_id <=", value, "assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdIn(List<Integer> values) {
			addCriterion("asset_state_id in", values, "assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdNotIn(List<Integer> values) {
			addCriterion("asset_state_id not in", values, "assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdBetween(Integer value1, Integer value2) {
			addCriterion("asset_state_id between", value1, value2,
					"assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetStateIdNotBetween(Integer value1, Integer value2) {
			addCriterion("asset_state_id not between", value1, value2,
					"assetStateId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdIsNull() {
			addCriterion("asset_kind_id is null");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdIsNotNull() {
			addCriterion("asset_kind_id is not null");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdEqualTo(Integer value) {
			addCriterion("asset_kind_id =", value, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdNotEqualTo(Integer value) {
			addCriterion("asset_kind_id <>", value, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdGreaterThan(Integer value) {
			addCriterion("asset_kind_id >", value, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("asset_kind_id >=", value, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdLessThan(Integer value) {
			addCriterion("asset_kind_id <", value, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdLessThanOrEqualTo(Integer value) {
			addCriterion("asset_kind_id <=", value, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdIn(List<Integer> values) {
			addCriterion("asset_kind_id in", values, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdNotIn(List<Integer> values) {
			addCriterion("asset_kind_id not in", values, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdBetween(Integer value1, Integer value2) {
			addCriterion("asset_kind_id between", value1, value2, "assetKindId");
			return (Criteria) this;
		}

		public Criteria andAssetKindIdNotBetween(Integer value1, Integer value2) {
			addCriterion("asset_kind_id not between", value1, value2,
					"assetKindId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNull() {
			addCriterion("account_id is null");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNotNull() {
			addCriterion("account_id is not null");
			return (Criteria) this;
		}

		public Criteria andAccountIdEqualTo(Integer value) {
			addCriterion("account_id =", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotEqualTo(Integer value) {
			addCriterion("account_id <>", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThan(Integer value) {
			addCriterion("account_id >", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("account_id >=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThan(Integer value) {
			addCriterion("account_id <", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
			addCriterion("account_id <=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIn(List<Integer> values) {
			addCriterion("account_id in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotIn(List<Integer> values) {
			addCriterion("account_id not in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdBetween(Integer value1, Integer value2) {
			addCriterion("account_id between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
			addCriterion("account_id not between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledIsNull() {
			addCriterion("asset_is_enabled is null");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledIsNotNull() {
			addCriterion("asset_is_enabled is not null");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledEqualTo(String value) {
			addCriterion("asset_is_enabled =", value, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledNotEqualTo(String value) {
			addCriterion("asset_is_enabled <>", value, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledGreaterThan(String value) {
			addCriterion("asset_is_enabled >", value, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledGreaterThanOrEqualTo(String value) {
			addCriterion("asset_is_enabled >=", value, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledLessThan(String value) {
			addCriterion("asset_is_enabled <", value, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledLessThanOrEqualTo(String value) {
			addCriterion("asset_is_enabled <=", value, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledLike(String value) {
			addCriterion("asset_is_enabled like", value, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledNotLike(String value) {
			addCriterion("asset_is_enabled not like", value, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledIn(List<String> values) {
			addCriterion("asset_is_enabled in", values, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledNotIn(List<String> values) {
			addCriterion("asset_is_enabled not in", values, "assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledBetween(String value1, String value2) {
			addCriterion("asset_is_enabled between", value1, value2,
					"assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsEnabledNotBetween(String value1, String value2) {
			addCriterion("asset_is_enabled not between", value1, value2,
					"assetIsEnabled");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleIsNull() {
			addCriterion("asset_is_visible is null");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleIsNotNull() {
			addCriterion("asset_is_visible is not null");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleEqualTo(String value) {
			addCriterion("asset_is_visible =", value, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleNotEqualTo(String value) {
			addCriterion("asset_is_visible <>", value, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleGreaterThan(String value) {
			addCriterion("asset_is_visible >", value, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleGreaterThanOrEqualTo(String value) {
			addCriterion("asset_is_visible >=", value, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleLessThan(String value) {
			addCriterion("asset_is_visible <", value, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleLessThanOrEqualTo(String value) {
			addCriterion("asset_is_visible <=", value, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleLike(String value) {
			addCriterion("asset_is_visible like", value, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleNotLike(String value) {
			addCriterion("asset_is_visible not like", value, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleIn(List<String> values) {
			addCriterion("asset_is_visible in", values, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleNotIn(List<String> values) {
			addCriterion("asset_is_visible not in", values, "assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleBetween(String value1, String value2) {
			addCriterion("asset_is_visible between", value1, value2,
					"assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetIsVisibleNotBetween(String value1, String value2) {
			addCriterion("asset_is_visible not between", value1, value2,
					"assetIsVisible");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateIsNull() {
			addCriterion("asset_create_date is null");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateIsNotNull() {
			addCriterion("asset_create_date is not null");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateEqualTo(Date value) {
			addCriterion("asset_create_date =", value, "assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateNotEqualTo(Date value) {
			addCriterion("asset_create_date <>", value, "assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateGreaterThan(Date value) {
			addCriterion("asset_create_date >", value, "assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("asset_create_date >=", value, "assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateLessThan(Date value) {
			addCriterion("asset_create_date <", value, "assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("asset_create_date <=", value, "assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateIn(List<Date> values) {
			addCriterion("asset_create_date in", values, "assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateNotIn(List<Date> values) {
			addCriterion("asset_create_date not in", values, "assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateBetween(Date value1, Date value2) {
			addCriterion("asset_create_date between", value1, value2,
					"assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("asset_create_date not between", value1, value2,
					"assetCreateDate");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManIsNull() {
			addCriterion("asset_create_man is null");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManIsNotNull() {
			addCriterion("asset_create_man is not null");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManEqualTo(String value) {
			addCriterion("asset_create_man =", value, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManNotEqualTo(String value) {
			addCriterion("asset_create_man <>", value, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManGreaterThan(String value) {
			addCriterion("asset_create_man >", value, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManGreaterThanOrEqualTo(String value) {
			addCriterion("asset_create_man >=", value, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManLessThan(String value) {
			addCriterion("asset_create_man <", value, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManLessThanOrEqualTo(String value) {
			addCriterion("asset_create_man <=", value, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManLike(String value) {
			addCriterion("asset_create_man like", value, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManNotLike(String value) {
			addCriterion("asset_create_man not like", value, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManIn(List<String> values) {
			addCriterion("asset_create_man in", values, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManNotIn(List<String> values) {
			addCriterion("asset_create_man not in", values, "assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManBetween(String value1, String value2) {
			addCriterion("asset_create_man between", value1, value2,
					"assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetCreateManNotBetween(String value1, String value2) {
			addCriterion("asset_create_man not between", value1, value2,
					"assetCreateMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateIsNull() {
			addCriterion("asset_modify_date is null");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateIsNotNull() {
			addCriterion("asset_modify_date is not null");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateEqualTo(Date value) {
			addCriterion("asset_modify_date =", value, "assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateNotEqualTo(Date value) {
			addCriterion("asset_modify_date <>", value, "assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateGreaterThan(Date value) {
			addCriterion("asset_modify_date >", value, "assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateGreaterThanOrEqualTo(Date value) {
			addCriterion("asset_modify_date >=", value, "assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateLessThan(Date value) {
			addCriterion("asset_modify_date <", value, "assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateLessThanOrEqualTo(Date value) {
			addCriterion("asset_modify_date <=", value, "assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateIn(List<Date> values) {
			addCriterion("asset_modify_date in", values, "assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateNotIn(List<Date> values) {
			addCriterion("asset_modify_date not in", values, "assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateBetween(Date value1, Date value2) {
			addCriterion("asset_modify_date between", value1, value2,
					"assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyDateNotBetween(Date value1, Date value2) {
			addCriterion("asset_modify_date not between", value1, value2,
					"assetModifyDate");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManIsNull() {
			addCriterion("asset_modify_man is null");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManIsNotNull() {
			addCriterion("asset_modify_man is not null");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManEqualTo(String value) {
			addCriterion("asset_modify_man =", value, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManNotEqualTo(String value) {
			addCriterion("asset_modify_man <>", value, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManGreaterThan(String value) {
			addCriterion("asset_modify_man >", value, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManGreaterThanOrEqualTo(String value) {
			addCriterion("asset_modify_man >=", value, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManLessThan(String value) {
			addCriterion("asset_modify_man <", value, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManLessThanOrEqualTo(String value) {
			addCriterion("asset_modify_man <=", value, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManLike(String value) {
			addCriterion("asset_modify_man like", value, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManNotLike(String value) {
			addCriterion("asset_modify_man not like", value, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManIn(List<String> values) {
			addCriterion("asset_modify_man in", values, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManNotIn(List<String> values) {
			addCriterion("asset_modify_man not in", values, "assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManBetween(String value1, String value2) {
			addCriterion("asset_modify_man between", value1, value2,
					"assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetModifyManNotBetween(String value1, String value2) {
			addCriterion("asset_modify_man not between", value1, value2,
					"assetModifyMan");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoIsNull() {
			addCriterion("asset_explain_info is null");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoIsNotNull() {
			addCriterion("asset_explain_info is not null");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoEqualTo(String value) {
			addCriterion("asset_explain_info =", value, "assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoNotEqualTo(String value) {
			addCriterion("asset_explain_info <>", value, "assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoGreaterThan(String value) {
			addCriterion("asset_explain_info >", value, "assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoGreaterThanOrEqualTo(String value) {
			addCriterion("asset_explain_info >=", value, "assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoLessThan(String value) {
			addCriterion("asset_explain_info <", value, "assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoLessThanOrEqualTo(String value) {
			addCriterion("asset_explain_info <=", value, "assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoLike(String value) {
			addCriterion("asset_explain_info like", value, "assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoNotLike(String value) {
			addCriterion("asset_explain_info not like", value,
					"assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoIn(List<String> values) {
			addCriterion("asset_explain_info in", values, "assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoNotIn(List<String> values) {
			addCriterion("asset_explain_info not in", values,
					"assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoBetween(String value1, String value2) {
			addCriterion("asset_explain_info between", value1, value2,
					"assetExplainInfo");
			return (Criteria) this;
		}

		public Criteria andAssetExplainInfoNotBetween(String value1,
				String value2) {
			addCriterion("asset_explain_info not between", value1, value2,
					"assetExplainInfo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_list
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 10 21:48:43 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}