package com.canco.assetstockin.model;

import java.util.ArrayList;
import java.util.List;

public class StockInInfoListExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public StockInInfoListExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStockInInfoIdIsNull() {
			addCriterion("stock_in_info_id is null");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdIsNotNull() {
			addCriterion("stock_in_info_id is not null");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdEqualTo(Integer value) {
			addCriterion("stock_in_info_id =", value, "stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdNotEqualTo(Integer value) {
			addCriterion("stock_in_info_id <>", value, "stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdGreaterThan(Integer value) {
			addCriterion("stock_in_info_id >", value, "stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("stock_in_info_id >=", value, "stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdLessThan(Integer value) {
			addCriterion("stock_in_info_id <", value, "stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdLessThanOrEqualTo(Integer value) {
			addCriterion("stock_in_info_id <=", value, "stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdIn(List<Integer> values) {
			addCriterion("stock_in_info_id in", values, "stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdNotIn(List<Integer> values) {
			addCriterion("stock_in_info_id not in", values, "stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdBetween(Integer value1, Integer value2) {
			addCriterion("stock_in_info_id between", value1, value2,
					"stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("stock_in_info_id not between", value1, value2,
					"stockInInfoId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdIsNull() {
			addCriterion("stock_in_info_stock_in_id is null");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdIsNotNull() {
			addCriterion("stock_in_info_stock_in_id is not null");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdEqualTo(Integer value) {
			addCriterion("stock_in_info_stock_in_id =", value,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdNotEqualTo(Integer value) {
			addCriterion("stock_in_info_stock_in_id <>", value,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdGreaterThan(Integer value) {
			addCriterion("stock_in_info_stock_in_id >", value,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("stock_in_info_stock_in_id >=", value,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdLessThan(Integer value) {
			addCriterion("stock_in_info_stock_in_id <", value,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdLessThanOrEqualTo(Integer value) {
			addCriterion("stock_in_info_stock_in_id <=", value,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdIn(List<Integer> values) {
			addCriterion("stock_in_info_stock_in_id in", values,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdNotIn(List<Integer> values) {
			addCriterion("stock_in_info_stock_in_id not in", values,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdBetween(Integer value1,
				Integer value2) {
			addCriterion("stock_in_info_stock_in_id between", value1, value2,
					"stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoStockInIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("stock_in_info_stock_in_id not between", value1,
					value2, "stockInInfoStockInId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdIsNull() {
			addCriterion("stock_in_info_asset_id is null");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdIsNotNull() {
			addCriterion("stock_in_info_asset_id is not null");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdEqualTo(Integer value) {
			addCriterion("stock_in_info_asset_id =", value,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdNotEqualTo(Integer value) {
			addCriterion("stock_in_info_asset_id <>", value,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdGreaterThan(Integer value) {
			addCriterion("stock_in_info_asset_id >", value,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("stock_in_info_asset_id >=", value,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdLessThan(Integer value) {
			addCriterion("stock_in_info_asset_id <", value,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdLessThanOrEqualTo(Integer value) {
			addCriterion("stock_in_info_asset_id <=", value,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdIn(List<Integer> values) {
			addCriterion("stock_in_info_asset_id in", values,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdNotIn(List<Integer> values) {
			addCriterion("stock_in_info_asset_id not in", values,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdBetween(Integer value1,
				Integer value2) {
			addCriterion("stock_in_info_asset_id between", value1, value2,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoAssetIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("stock_in_info_asset_id not between", value1, value2,
					"stockInInfoAssetId");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleIsNull() {
			addCriterion("stock_in_info_is_visible is null");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleIsNotNull() {
			addCriterion("stock_in_info_is_visible is not null");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleEqualTo(String value) {
			addCriterion("stock_in_info_is_visible =", value,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleNotEqualTo(String value) {
			addCriterion("stock_in_info_is_visible <>", value,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleGreaterThan(String value) {
			addCriterion("stock_in_info_is_visible >", value,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleGreaterThanOrEqualTo(String value) {
			addCriterion("stock_in_info_is_visible >=", value,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleLessThan(String value) {
			addCriterion("stock_in_info_is_visible <", value,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleLessThanOrEqualTo(String value) {
			addCriterion("stock_in_info_is_visible <=", value,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleLike(String value) {
			addCriterion("stock_in_info_is_visible like", value,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleNotLike(String value) {
			addCriterion("stock_in_info_is_visible not like", value,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleIn(List<String> values) {
			addCriterion("stock_in_info_is_visible in", values,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleNotIn(List<String> values) {
			addCriterion("stock_in_info_is_visible not in", values,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleBetween(String value1,
				String value2) {
			addCriterion("stock_in_info_is_visible between", value1, value2,
					"stockInInfoIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInInfoIsVisibleNotBetween(String value1,
				String value2) {
			addCriterion("stock_in_info_is_visible not between", value1,
					value2, "stockInInfoIsVisible");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_in_info_list
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 10 21:48:43 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    //@CodeGen 手动添加或生成 begin
    protected int start;
    protected int offset;

    public int getOffset() {
        return offset;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }

    public int getStart() {
        return start;
    }

    public void setStart(int start) {
        this.start = start;
    }
    //@CodeGen 手动添加或生成 end
}