package com.canco.assetstockin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StockInListExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public StockInListExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStockInIdIsNull() {
			addCriterion("stock_in_id is null");
			return (Criteria) this;
		}

		public Criteria andStockInIdIsNotNull() {
			addCriterion("stock_in_id is not null");
			return (Criteria) this;
		}

		public Criteria andStockInIdEqualTo(Integer value) {
			addCriterion("stock_in_id =", value, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdNotEqualTo(Integer value) {
			addCriterion("stock_in_id <>", value, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdGreaterThan(Integer value) {
			addCriterion("stock_in_id >", value, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("stock_in_id >=", value, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdLessThan(Integer value) {
			addCriterion("stock_in_id <", value, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdLessThanOrEqualTo(Integer value) {
			addCriterion("stock_in_id <=", value, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdIn(List<Integer> values) {
			addCriterion("stock_in_id in", values, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdNotIn(List<Integer> values) {
			addCriterion("stock_in_id not in", values, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdBetween(Integer value1, Integer value2) {
			addCriterion("stock_in_id between", value1, value2, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInIdNotBetween(Integer value1, Integer value2) {
			addCriterion("stock_in_id not between", value1, value2, "stockInId");
			return (Criteria) this;
		}

		public Criteria andStockInNoIsNull() {
			addCriterion("stock_in_no is null");
			return (Criteria) this;
		}

		public Criteria andStockInNoIsNotNull() {
			addCriterion("stock_in_no is not null");
			return (Criteria) this;
		}

		public Criteria andStockInNoEqualTo(String value) {
			addCriterion("stock_in_no =", value, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoNotEqualTo(String value) {
			addCriterion("stock_in_no <>", value, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoGreaterThan(String value) {
			addCriterion("stock_in_no >", value, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoGreaterThanOrEqualTo(String value) {
			addCriterion("stock_in_no >=", value, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoLessThan(String value) {
			addCriterion("stock_in_no <", value, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoLessThanOrEqualTo(String value) {
			addCriterion("stock_in_no <=", value, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoLike(String value) {
			addCriterion("stock_in_no like", value, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoNotLike(String value) {
			addCriterion("stock_in_no not like", value, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoIn(List<String> values) {
			addCriterion("stock_in_no in", values, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoNotIn(List<String> values) {
			addCriterion("stock_in_no not in", values, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoBetween(String value1, String value2) {
			addCriterion("stock_in_no between", value1, value2, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andStockInNoNotBetween(String value1, String value2) {
			addCriterion("stock_in_no not between", value1, value2, "stockInNo");
			return (Criteria) this;
		}

		public Criteria andInOrganIdIsNull() {
			addCriterion("in_organ_id is null");
			return (Criteria) this;
		}

		public Criteria andInOrganIdIsNotNull() {
			addCriterion("in_organ_id is not null");
			return (Criteria) this;
		}

		public Criteria andInOrganIdEqualTo(Integer value) {
			addCriterion("in_organ_id =", value, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdNotEqualTo(Integer value) {
			addCriterion("in_organ_id <>", value, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdGreaterThan(Integer value) {
			addCriterion("in_organ_id >", value, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("in_organ_id >=", value, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdLessThan(Integer value) {
			addCriterion("in_organ_id <", value, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdLessThanOrEqualTo(Integer value) {
			addCriterion("in_organ_id <=", value, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdIn(List<Integer> values) {
			addCriterion("in_organ_id in", values, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdNotIn(List<Integer> values) {
			addCriterion("in_organ_id not in", values, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdBetween(Integer value1, Integer value2) {
			addCriterion("in_organ_id between", value1, value2, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInOrganIdNotBetween(Integer value1, Integer value2) {
			addCriterion("in_organ_id not between", value1, value2, "inOrganId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdIsNull() {
			addCriterion("in_unit_id is null");
			return (Criteria) this;
		}

		public Criteria andInUnitIdIsNotNull() {
			addCriterion("in_unit_id is not null");
			return (Criteria) this;
		}

		public Criteria andInUnitIdEqualTo(Integer value) {
			addCriterion("in_unit_id =", value, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdNotEqualTo(Integer value) {
			addCriterion("in_unit_id <>", value, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdGreaterThan(Integer value) {
			addCriterion("in_unit_id >", value, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("in_unit_id >=", value, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdLessThan(Integer value) {
			addCriterion("in_unit_id <", value, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdLessThanOrEqualTo(Integer value) {
			addCriterion("in_unit_id <=", value, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdIn(List<Integer> values) {
			addCriterion("in_unit_id in", values, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdNotIn(List<Integer> values) {
			addCriterion("in_unit_id not in", values, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdBetween(Integer value1, Integer value2) {
			addCriterion("in_unit_id between", value1, value2, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInUnitIdNotBetween(Integer value1, Integer value2) {
			addCriterion("in_unit_id not between", value1, value2, "inUnitId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdIsNull() {
			addCriterion("in_employee_id is null");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdIsNotNull() {
			addCriterion("in_employee_id is not null");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdEqualTo(Integer value) {
			addCriterion("in_employee_id =", value, "inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdNotEqualTo(Integer value) {
			addCriterion("in_employee_id <>", value, "inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdGreaterThan(Integer value) {
			addCriterion("in_employee_id >", value, "inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("in_employee_id >=", value, "inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdLessThan(Integer value) {
			addCriterion("in_employee_id <", value, "inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdLessThanOrEqualTo(Integer value) {
			addCriterion("in_employee_id <=", value, "inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdIn(List<Integer> values) {
			addCriterion("in_employee_id in", values, "inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdNotIn(List<Integer> values) {
			addCriterion("in_employee_id not in", values, "inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdBetween(Integer value1, Integer value2) {
			addCriterion("in_employee_id between", value1, value2,
					"inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andInEmployeeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("in_employee_id not between", value1, value2,
					"inEmployeeId");
			return (Criteria) this;
		}

		public Criteria andStockInInDateIsNull() {
			addCriterion("stock_in_in_date is null");
			return (Criteria) this;
		}

		public Criteria andStockInInDateIsNotNull() {
			addCriterion("stock_in_in_date is not null");
			return (Criteria) this;
		}

		public Criteria andStockInInDateEqualTo(Date value) {
			addCriterion("stock_in_in_date =", value, "stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateNotEqualTo(Date value) {
			addCriterion("stock_in_in_date <>", value, "stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateGreaterThan(Date value) {
			addCriterion("stock_in_in_date >", value, "stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateGreaterThanOrEqualTo(Date value) {
			addCriterion("stock_in_in_date >=", value, "stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateLessThan(Date value) {
			addCriterion("stock_in_in_date <", value, "stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateLessThanOrEqualTo(Date value) {
			addCriterion("stock_in_in_date <=", value, "stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateIn(List<Date> values) {
			addCriterion("stock_in_in_date in", values, "stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateNotIn(List<Date> values) {
			addCriterion("stock_in_in_date not in", values, "stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateBetween(Date value1, Date value2) {
			addCriterion("stock_in_in_date between", value1, value2,
					"stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInInDateNotBetween(Date value1, Date value2) {
			addCriterion("stock_in_in_date not between", value1, value2,
					"stockInInDate");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleIsNull() {
			addCriterion("stock_in_is_visible is null");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleIsNotNull() {
			addCriterion("stock_in_is_visible is not null");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleEqualTo(String value) {
			addCriterion("stock_in_is_visible =", value, "stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleNotEqualTo(String value) {
			addCriterion("stock_in_is_visible <>", value, "stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleGreaterThan(String value) {
			addCriterion("stock_in_is_visible >", value, "stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleGreaterThanOrEqualTo(String value) {
			addCriterion("stock_in_is_visible >=", value, "stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleLessThan(String value) {
			addCriterion("stock_in_is_visible <", value, "stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleLessThanOrEqualTo(String value) {
			addCriterion("stock_in_is_visible <=", value, "stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleLike(String value) {
			addCriterion("stock_in_is_visible like", value, "stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleNotLike(String value) {
			addCriterion("stock_in_is_visible not like", value,
					"stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleIn(List<String> values) {
			addCriterion("stock_in_is_visible in", values, "stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleNotIn(List<String> values) {
			addCriterion("stock_in_is_visible not in", values,
					"stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleBetween(String value1, String value2) {
			addCriterion("stock_in_is_visible between", value1, value2,
					"stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInIsVisibleNotBetween(String value1,
				String value2) {
			addCriterion("stock_in_is_visible not between", value1, value2,
					"stockInIsVisible");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateIsNull() {
			addCriterion("stock_in_create_date is null");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateIsNotNull() {
			addCriterion("stock_in_create_date is not null");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateEqualTo(Date value) {
			addCriterion("stock_in_create_date =", value, "stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateNotEqualTo(Date value) {
			addCriterion("stock_in_create_date <>", value, "stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateGreaterThan(Date value) {
			addCriterion("stock_in_create_date >", value, "stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("stock_in_create_date >=", value, "stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateLessThan(Date value) {
			addCriterion("stock_in_create_date <", value, "stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("stock_in_create_date <=", value, "stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateIn(List<Date> values) {
			addCriterion("stock_in_create_date in", values, "stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateNotIn(List<Date> values) {
			addCriterion("stock_in_create_date not in", values,
					"stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateBetween(Date value1, Date value2) {
			addCriterion("stock_in_create_date between", value1, value2,
					"stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("stock_in_create_date not between", value1, value2,
					"stockInCreateDate");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManIsNull() {
			addCriterion("stock_in_create_man is null");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManIsNotNull() {
			addCriterion("stock_in_create_man is not null");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManEqualTo(String value) {
			addCriterion("stock_in_create_man =", value, "stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManNotEqualTo(String value) {
			addCriterion("stock_in_create_man <>", value, "stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManGreaterThan(String value) {
			addCriterion("stock_in_create_man >", value, "stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManGreaterThanOrEqualTo(String value) {
			addCriterion("stock_in_create_man >=", value, "stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManLessThan(String value) {
			addCriterion("stock_in_create_man <", value, "stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManLessThanOrEqualTo(String value) {
			addCriterion("stock_in_create_man <=", value, "stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManLike(String value) {
			addCriterion("stock_in_create_man like", value, "stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManNotLike(String value) {
			addCriterion("stock_in_create_man not like", value,
					"stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManIn(List<String> values) {
			addCriterion("stock_in_create_man in", values, "stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManNotIn(List<String> values) {
			addCriterion("stock_in_create_man not in", values,
					"stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManBetween(String value1, String value2) {
			addCriterion("stock_in_create_man between", value1, value2,
					"stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInCreateManNotBetween(String value1,
				String value2) {
			addCriterion("stock_in_create_man not between", value1, value2,
					"stockInCreateMan");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoIsNull() {
			addCriterion("stock_in_explain_info is null");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoIsNotNull() {
			addCriterion("stock_in_explain_info is not null");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoEqualTo(String value) {
			addCriterion("stock_in_explain_info =", value, "stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoNotEqualTo(String value) {
			addCriterion("stock_in_explain_info <>", value,
					"stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoGreaterThan(String value) {
			addCriterion("stock_in_explain_info >", value, "stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoGreaterThanOrEqualTo(String value) {
			addCriterion("stock_in_explain_info >=", value,
					"stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoLessThan(String value) {
			addCriterion("stock_in_explain_info <", value, "stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoLessThanOrEqualTo(String value) {
			addCriterion("stock_in_explain_info <=", value,
					"stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoLike(String value) {
			addCriterion("stock_in_explain_info like", value,
					"stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoNotLike(String value) {
			addCriterion("stock_in_explain_info not like", value,
					"stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoIn(List<String> values) {
			addCriterion("stock_in_explain_info in", values,
					"stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoNotIn(List<String> values) {
			addCriterion("stock_in_explain_info not in", values,
					"stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoBetween(String value1,
				String value2) {
			addCriterion("stock_in_explain_info between", value1, value2,
					"stockInExplainInfo");
			return (Criteria) this;
		}

		public Criteria andStockInExplainInfoNotBetween(String value1,
				String value2) {
			addCriterion("stock_in_explain_info not between", value1, value2,
					"stockInExplainInfo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_in_list
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 10 21:48:43 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}