package com.canco.assetstockin.model;

import com.canco.common.util.CustomDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.Date;

public class StockInList {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.stock_in_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private Integer stockInId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.stock_in_no
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private String stockInNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.in_organ_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private Integer inOrganId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.in_unit_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private Integer inUnitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.in_employee_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private Integer inEmployeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.stock_in_in_date
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private Date stockInInDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.stock_in_is_visible
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private String stockInIsVisible;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.stock_in_create_date
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private Date stockInCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.stock_in_create_man
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private String stockInCreateMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_in_list.stock_in_explain_info
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	private String stockInExplainInfo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.stock_in_id
	 * @return  the value of stock_in_list.stock_in_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Integer getStockInId() {
		return stockInId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.stock_in_id
	 * @param stockInId  the value for stock_in_list.stock_in_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setStockInId(Integer stockInId) {
		this.stockInId = stockInId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.stock_in_no
	 * @return  the value of stock_in_list.stock_in_no
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public String getStockInNo() {
		return stockInNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.stock_in_no
	 * @param stockInNo  the value for stock_in_list.stock_in_no
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setStockInNo(String stockInNo) {
		this.stockInNo = stockInNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.in_organ_id
	 * @return  the value of stock_in_list.in_organ_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Integer getInOrganId() {
		return inOrganId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.in_organ_id
	 * @param inOrganId  the value for stock_in_list.in_organ_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setInOrganId(Integer inOrganId) {
		this.inOrganId = inOrganId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.in_unit_id
	 * @return  the value of stock_in_list.in_unit_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Integer getInUnitId() {
		return inUnitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.in_unit_id
	 * @param inUnitId  the value for stock_in_list.in_unit_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setInUnitId(Integer inUnitId) {
		this.inUnitId = inUnitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.in_employee_id
	 * @return  the value of stock_in_list.in_employee_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public Integer getInEmployeeId() {
		return inEmployeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.in_employee_id
	 * @param inEmployeeId  the value for stock_in_list.in_employee_id
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setInEmployeeId(Integer inEmployeeId) {
		this.inEmployeeId = inEmployeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.stock_in_in_date
	 * @return  the value of stock_in_list.stock_in_in_date
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
    @JsonSerialize(using = CustomDateSerializer.class)
	public Date getStockInInDate() {
		return stockInInDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.stock_in_in_date
	 * @param stockInInDate  the value for stock_in_list.stock_in_in_date
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setStockInInDate(Date stockInInDate) {
		this.stockInInDate = stockInInDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.stock_in_is_visible
	 * @return  the value of stock_in_list.stock_in_is_visible
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public String getStockInIsVisible() {
		return stockInIsVisible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.stock_in_is_visible
	 * @param stockInIsVisible  the value for stock_in_list.stock_in_is_visible
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setStockInIsVisible(String stockInIsVisible) {
		this.stockInIsVisible = stockInIsVisible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.stock_in_create_date
	 * @return  the value of stock_in_list.stock_in_create_date
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
    @JsonSerialize(using = CustomDateSerializer.class)
	public Date getStockInCreateDate() {
		return stockInCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.stock_in_create_date
	 * @param stockInCreateDate  the value for stock_in_list.stock_in_create_date
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setStockInCreateDate(Date stockInCreateDate) {
		this.stockInCreateDate = stockInCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.stock_in_create_man
	 * @return  the value of stock_in_list.stock_in_create_man
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public String getStockInCreateMan() {
		return stockInCreateMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.stock_in_create_man
	 * @param stockInCreateMan  the value for stock_in_list.stock_in_create_man
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setStockInCreateMan(String stockInCreateMan) {
		this.stockInCreateMan = stockInCreateMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_in_list.stock_in_explain_info
	 * @return  the value of stock_in_list.stock_in_explain_info
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public String getStockInExplainInfo() {
		return stockInExplainInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_in_list.stock_in_explain_info
	 * @param stockInExplainInfo  the value for stock_in_list.stock_in_explain_info
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	public void setStockInExplainInfo(String stockInExplainInfo) {
		this.stockInExplainInfo = stockInExplainInfo;
	}

    //@CodeGen start
    public StockInList(){
        this.setStockInNo("");
        this.setStockInNo("");
        this.setInOrganId(0);
        this.setInUnitId(0);
        this.setInEmployeeId(0);
        this.setStockInInDate(new Date());
        this.setStockInIsVisible("1");
        this.setStockInCreateDate(new Date());
        this.setStockInCreateMan("");
    }

	@Override
	public String toString() {
		return "StockInList [stockInId=" + stockInId + ", stockInNo="
				+ stockInNo + ", inOrganId=" + inOrganId + ", inUnitId="
				+ inUnitId + ", inEmployeeId=" + inEmployeeId
				+ ", stockInInDate=" + stockInInDate + ", stockInIsVisible="
				+ stockInIsVisible + ", stockInCreateDate=" + stockInCreateDate
				+ ", stockInCreateMan=" + stockInCreateMan
				+ ", stockInExplainInfo=" + stockInExplainInfo + "]";
	}

    //@CodeGen end

}