package com.student.registration.dao;

import com.student.registration.model.ClassList;
import com.student.registration.model.ClassListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Component;

@Component("ClassListMapper")
public interface ClassListMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
//	@Cacheable(value = "serviceCache")
    int countByExample(ClassListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@CacheEvict(value = "serviceCache")
    int deleteByExample(ClassListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@CacheEvict(value = "serviceCache")
    int deleteByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@CacheEvict(value = "serviceCache")
    int insert(ClassList record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@CacheEvict(value = "serviceCache")
    int insertSelective(ClassList record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@Cacheable(value = "serviceCache")
    List<ClassList> selectByExample(ClassListExample example);

    //	@Cacheable(value = "serviceCache")
    List<ClassList> selectByExampleAndLimit(ClassListExample example);
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@Cacheable(value = "serviceCache")
    ClassList selectByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@CacheEvict(value = "serviceCache")
    int updateByExampleSelective(@Param("record") ClassList record,
                                 @Param("example") ClassListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@CacheEvict(value = "serviceCache")
    int updateByExample(@Param("record") ClassList record,
                        @Param("example") ClassListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@CacheEvict(value = "serviceCache")
    int updateByPrimaryKeySelective(ClassList record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table class_list
     * @mbggenerated  Mon Nov 03 12:57:56 CST 2014
     */
    //@CacheEvict(value = "serviceCache")
    int updateByPrimaryKey(ClassList record);
}