package com.student.registration.dao;

import com.student.registration.model.ClassList;
import com.student.registration.model.ClassListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component("ClassListMapper")
public interface ClassListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int countByExample(ClassListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int deleteByExample(ClassListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int deleteByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int insert(ClassList record);

	int myinsert(ClassList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int insertSelective(ClassList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    List<ClassList> selectByExample(ClassListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    ClassList selectByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") ClassList record, @Param("example") ClassListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int updateByExample(@Param("record") ClassList record, @Param("example") ClassListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int updateByPrimaryKeySelective(ClassList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_list
     *
     * @mbggenerated Thu Oct 30 20:04:42 CST 2014
     */
    int updateByPrimaryKey(ClassList record);
}