package com.student.registration.dao;

import org.apache.ibatis.annotations.Param;
import com.student.registration.model.User;
import com.student.registration.model.UserExample;

import java.util.List;

import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Component;

@Component("UserMapper")
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//	@Cacheable(value = "serviceCache")
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//	 @CacheEvict(value = "serviceCache")
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//	 @CacheEvict(value = "serviceCache")
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//	 @CacheEvict(value = "serviceCache")
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//	 @CacheEvict(value = "serviceCache")
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//	@Cacheable(value = "serviceCache")
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//	@Cacheable(value = "serviceCache")
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//    @CacheEvict(value = "serviceCache")
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//    @CacheEvict(value = "serviceCache")
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//    @CacheEvict(value = "serviceCache")
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 21 20:25:50 CST 2014
     */
//    @CacheEvict(value = "serviceCache")
    int updateByPrimaryKey(User record);
}