package com.canco.assetstockin.dao;


import java.util.List;

import com.canco.assetstockin.model.AssetList;
import com.canco.assetstockin.model.AssetListExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component("AssetListMapper")
public interface AssetListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int countByExample(AssetListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int deleteByExample(AssetListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int deleteByPrimaryKey(Integer assetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int insert(AssetList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int insertSelective(AssetList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	List<AssetList> selectByExample(AssetListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	AssetList selectByPrimaryKey(Integer assetId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AssetList record,
                                 @Param("example") AssetListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByExample(@Param("record") AssetList record,
                        @Param("example") AssetListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByPrimaryKeySelective(AssetList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asset_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByPrimaryKey(AssetList record);
}