package com.canco.assetstockin.dao;

import java.util.List;

import com.canco.assetstockin.model.StockInList;
import com.canco.assetstockin.model.StockInListExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component("StockInListMapper")
public interface StockInListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int countByExample(StockInListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int deleteByExample(StockInListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int deleteByPrimaryKey(Integer stockInId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int insert(StockInList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int insertSelective(StockInList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	List<StockInList> selectByExample(StockInListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	StockInList selectByPrimaryKey(Integer stockInId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByExampleSelective(@Param("record") StockInList record,
                                 @Param("example") StockInListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByExample(@Param("record") StockInList record,
                        @Param("example") StockInListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByPrimaryKeySelective(StockInList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByPrimaryKey(StockInList record);
}