package com.canco.assetstockin.dao;


import java.util.List;

import com.canco.assetstockin.model.*;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component("StockInInfoListMapper")
public interface StockInInfoListMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int countByExample(StockInInfoListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int deleteByExample(StockInInfoListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int deleteByPrimaryKey(Integer stockInInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int insert(StockInInfoList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int insertSelective(StockInInfoList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	List<StockInInfoList> selectByExample(StockInInfoListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	StockInInfoList selectByPrimaryKey(Integer stockInInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByExampleSelective(@Param("record") StockInInfoList record,
                                 @Param("example") StockInInfoListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByExample(@Param("record") StockInInfoList record,
                        @Param("example") StockInInfoListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByPrimaryKeySelective(StockInInfoList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stock_in_info_list
	 * @mbggenerated  Mon Dec 15 15:51:52 CST 2014
	 */
	int updateByPrimaryKey(StockInInfoList record);

    /**
     * 根据example里的查询条件选择中间关联表数据
     * @param example
     * @return
     */
    List<AssetStockList> selectAssetStockList(AssetStockListExample example);

    /**
     * 根据example里的查询条件选择不存在关联关系的资产列表
     * @param example
     * @return
     */
    List<AssetList> selectAssetListNotInStockInInfoList(AssetStockListExample example);
}